### ISSUE TITLE
Question about your article https://im5tu.io/article/2018/06/automated-builds-in-vsts-with-yml-build-definitions/

### ISSUE THREAD

**Issue by StefH** [Im5tu/im5tu-hugo#1]
In your article
https://im5tu.io/article/2018/06/automated-builds-in-vsts-with-yml-build-definitions/

You describe that you define the projects to build like:
``` yml
variables:
  buildConfiguration: 'Release'
  buildProjects: '**/*.csproj'
```

However do you know if it's possible to define a `;` separated list from projects?
Like
``` yml
variables:
  buildConfiguration: 'Release'
  buildProjects: './src/ClassLibrary1/ClassLibrary1.csproj;./src/ClassLibrary2/ClassLibrary2.csproj'
```

I tried this and it seems this fails?
